version: "3.3"

services: 
  twitter-slack:
    image: comworkio/twitter-slack:${UNIQ_VERSION}
    container_name: twitter-slack
    env_file: 
      - twitter_slack.env
    networks:
      - twitter-slack
  twitter-slack-redis:
    image: redis:6.2.6
    restart: always
    container_name: twitter-slack-redis
    networks:
      - twitter-slack
    volumes:
      - twitter-slack-redis-data:/data

volumes:
  twitter-slack-redis-data:

networks:
  twitter-slack:
    driver: bridge
