version: "3.3"

services: 
  social-bridge:
    image: comworkio/social-bridge:${SOCIAL_BRIDGE_VERSION}
    container_name: social-bridge
    env_file: 
      - twitter_slack.env
    networks:
      - social-bridge
  social-bridge-redis:
    image: redis:6.2.6
    restart: always
    container_name: social-bridge-redis
    networks:
      - social-bridge
    volumes:
      - social-bridge-redis/data

volumes:
  social-bridge-redis

networks:
  social-bridge:
    driver: bridge
