version: "3.3"

services: 
  twitter-slack:
    image: comworkio/twitter-slack:latest
    container_name: twitter-slack
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    networks:
      - twitter-slack
  twitter-slack-redis:
    image: redis:6.2.6
    restart: always
    container_name: twitter-slack-redis
    networks:
      - twitter-slack

networks:
  twitter-slack:
    driver: bridge
