version: "3.3"

services: 
  social-bridge:
    image: comworkio/social-bridge:${TWITTER_SLACK_VERSION}
    container_name: social-bridge
    env_file: 
      - twitter_slack.env
    networks:
      - social-bridge
  twitter-cross:
    image: comworkio/social-bridge:${TWITTER_SLACK_VERSION}
    container_name: twitter-cross
    env_file: 
      - twitter_cross.env
    networks:
      - social-bridge
  mastodon-cross:
    image: comworkio/social-bridge:${TWITTER_SLACK_VERSION}
    container_name: mastodon-cross
    env_file: 
      - mastodon_cross.env
    networks:
      - social-bridge
  social-bridge-redis:
    image: redis:6.2.6
    restart: always
    container_name: social-bridge-redis
    networks:
      - social-bridge
    volumes:
      - twitter-slack-redis-data:/data

volumes:
  twitter-slack-redis-data:

networks:
  social-bridge:
    driver: bridge
